module mat
contains
  attributes(global) subroutine matmul(a, b, c)
    implicit none
    real :: a(:,:), b(:,:), c(:,:), sum
    integer :: i,j,k,n
    n = size(a,1)
    i = blockDim%x * (blockIdx%x - 1) + threadIdx%x
    j = blockDim%y * (blockIdx%y - 1) + threadIdx%y

    if ((i <= n) .and. (j <= n)) then
      sum = 0.d0
      do k=1,n
        sum = sum + a(i,k)*b(k,j)
      enddo!k
      c(i,j) = sum
    endif
  end subroutine matmul 
end module mat
